import streamlit as pd_stream
import pandas as pd
import os

# Set up page styling and layout
pd_stream.set_page_config(page_title="AI Sports Betting Dashboard", layout="wide")

# Dashboard Title
pd_stream.markdown("# 🧠 Local AI Sports Prediction Engine")
pd_stream.markdown("### Monitor Ollama Analysis, Value Edges, and Betting Allocations")
pd_stream.write("---")

filename = "master_predictions_sheet.csv"

if not os.path.exists(filename):
    pd_stream.error(f"❌ Could not find '{filename}'. Please run `python ai_processing_engine.py` first to generate the dataset.")
else:
    # Read the data generated by your processing engine
    df = pd.read_csv(filename)
    
    # Sidebar control panel for parameters
    pd_stream.sidebar.header("⚙️ Bankroll Management")
    bankroll = pd_stream.sidebar.number_input("Total Betting Bankroll (\$)", min_value=10.0, value=1000.0, step=50.0)
    min_edge = pd_stream.sidebar.slider("Minimum Value Edge Cutoff (%)", min_value=0.0, max_value=15.0, value=1.0, step=0.5)
    
    # Filter by sport league category
    sports_available = ["ALL"] + list(df["Sport"].unique())
    selected_sport = pd_stream.sidebar.selectbox("Filter by League", sports_available)
    
    if selected_sport != "ALL":
        df = df[df["Sport"] == selected_sport]
        
    # Filter by minimum edge calculated
    df = df[df["Calculated Edge %"] >= min_edge]

    # --- KPI Metric Overview Panels ---
    total_games = len(df)
    active_bets = len(df[df["Recommended Bet"] != "❌ NO VALUE"])
    
    col1, col2, col3 = pd_stream.columns(3)
    col1.metric("Total Games Tracked", total_games)
    col2.metric("Active AI Buy Signals", active_bets)
    if active_bets > 0:
        max_edge_val = df["Calculated Edge %"].max()
        col3.metric("Top Market Discrepancy", f"+{max_edge_val}% Edge")
    else:
        col3.metric("Top Market Discrepancy", "0.0% Edge")
        
    pd_stream.write("### 🗂 Real-Time Selection Grid")
    
    # Clean up column tracking references internally
    if "Bet Allocation (\$)" in df.columns:
        allocation_col = "Bet Allocation (\$)"
    elif "Bet Allocation" in df.columns:
        allocation_col = "Bet Allocation"
    else:
        # Search for any column containing 'Allocation'
        allocation_col = [c for c in df.columns if "Allocation" in c][0]

    # Display the complete interactive sheet matrix
    pd_stream.dataframe(
        df,
        column_config={
            "Away American Odds": pd_stream.column_config.NumberColumn("Away Odds"),
            "Home American Odds": pd_stream.column_config.NumberColumn("Home Odds"),
            "AI Away Prob %": pd_stream.column_config.ProgressColumn("AI Away Prob %", format="%d%%", min_value=0, max_value=100),
            "AI Home Prob %": pd_stream.column_config.ProgressColumn("AI Home Prob %", format="%d%%", min_value=0, max_value=100),
            "Calculated Edge %": "Calculated Edge %",
            allocation_col: pd_stream.column_config.NumberColumn("Suggested Allocation", format="\$%.2f")
        },
        use_container_width=True,
        hide_index=True
    )
    
    # --- BLUEPRINT COPY STATIONS ---
    pd_stream.write("---")
    pd_stream.write("### 📋 Quick Copy Hub (Active Recommendations)")
    
    active_df = df[df["Recommended Bet"] != "❌ NO VALUE"]
    
    if active_df.empty:
        pd_stream.info("No active high-value plays matching your current filters.")
    else:
        # Loop through rows to display copyable text zones
        for idx, row in active_df.iterrows():
            with pd_stream.container():
                sport_label = row['Sport']
                matchup_title = f"{row['Away Team']} @ {row['Home Team']}"
                pick = row['Recommended Bet'].replace("🟢 ", "").replace("🔵 ", "")
                
                # Recalculate allocation dynamically
                orig_allocation_fraction = row[allocation_col] / 1000.0  
                adjusted_bet = round(orig_allocation_fraction * bankroll, 2)
                
                odds_val = row['Home American Odds'] if "HOME" in row['Recommended Bet'] else row['Away American Odds']
                odds_str = f"+{odds_val}" if odds_val > 0 else str(odds_val)
                
                copy_text = f"LEAGUE: {sport_label} | SELECTION: {pick} ({odds_str}) | RECOMMENDED RISK: \${adjusted_bet}"
                
                pd_stream.markdown(f"**📍 {matchup_title} ({sport_label})** — Edge: **+{row['Calculated Edge %']}%**")
                pd_stream.code(copy_text, language="text")
