import { GameRecord, SettledBet } from './types';

export const INITIAL_GAMES: GameRecord[] = [
  // --- LAYER 2: LIVE IN-PLAY EVENTS ---
  {
    id: 'game-1',
    sport: 'MLB',
    league: 'MLB',
    matchup: 'Los Angeles Dodgers @ San Diego Padres',
    engineLayer: '🔴 LAYER 2: LIVE',
    timeMetric: 'Inning 7 - Active',
    scoreTicker: 'LAD 5 - 4 SD',
    tonyBetOntario: '+125',
    betMgmOntario: '-105',
    edgeMarginPct: 7.3,
    aiActionDirective: '🔥 LIVE BUY',
    pickTeam: 'Los Angeles Dodgers',
    periodOrClock: 'Top 7th, 2 Outs'
  },
  {
    id: 'game-live-2',
    sport: 'MLB',
    league: 'MLB',
    matchup: 'Atlanta Braves @ Philadelphia Phillies',
    engineLayer: '🔴 LAYER 2: LIVE',
    timeMetric: 'Inning 8 - Active',
    scoreTicker: 'ATL 3 - 3 PHI',
    tonyBetOntario: '+110',
    betMgmOntario: '-115',
    edgeMarginPct: 4.2,
    aiActionDirective: '🔥 LIVE BUY',
    pickTeam: 'Atlanta Braves',
    periodOrClock: 'Bottom 8th, 1 Out'
  },
  {
    id: 'game-3',
    sport: 'NBA',
    league: 'NBA',
    matchup: 'Boston Celtics @ Miami Heat',
    engineLayer: '🔴 LAYER 2: LIVE',
    timeMetric: 'Q3 04:12',
    scoreTicker: 'BOS 88 - 82 MIA',
    tonyBetOntario: '-115',
    betMgmOntario: '-102',
    edgeMarginPct: 3.1,
    aiActionDirective: '🔥 LIVE BUY',
    pickTeam: 'Boston Celtics',
    periodOrClock: '3rd Quarter'
  },
  {
    id: 'game-live-4',
    sport: 'NBA',
    league: 'NBA',
    matchup: 'Milwaukee Bucks @ New York Knicks',
    engineLayer: '🔴 LAYER 2: LIVE',
    timeMetric: 'Q4 02:45',
    scoreTicker: 'MIL 104 - 106 NYK',
    tonyBetOntario: '+145',
    betMgmOntario: '+115',
    edgeMarginPct: 6.4,
    aiActionDirective: '🔥 LIVE BUY',
    pickTeam: 'Milwaukee Bucks',
    periodOrClock: '4th Quarter'
  },
  {
    id: 'game-4',
    sport: 'SOCCER',
    league: 'Premier League',
    matchup: 'Arsenal vs Chelsea',
    engineLayer: '🔴 LAYER 2: LIVE',
    timeMetric: '68:51 Live Ticker',
    scoreTicker: 'ARS 2 - 1 CHE',
    tonyBetOntario: '+140',
    betMgmOntario: '+120',
    edgeMarginPct: 3.8,
    aiActionDirective: '🔥 LIVE BUY',
    pickTeam: 'Arsenal',
    periodOrClock: '2nd Half'
  },
  {
    id: 'game-live-6',
    sport: 'SOCCER',
    league: 'La Liga',
    matchup: 'Real Madrid vs Barcelona',
    engineLayer: '🔴 LAYER 2: LIVE',
    timeMetric: '54:10 Live Ticker',
    scoreTicker: 'RMA 1 - 2 FCB',
    tonyBetOntario: '+185',
    betMgmOntario: '+150',
    edgeMarginPct: 6.9,
    aiActionDirective: '🔥 LIVE BUY',
    pickTeam: 'Barcelona',
    periodOrClock: '2nd Half'
  },
  {
    id: 'game-live-7',
    sport: 'SOCCER',
    league: 'Serie A',
    matchup: 'Inter Milan vs Juventus',
    engineLayer: '🔴 LAYER 2: LIVE',
    timeMetric: '72:30 Live Ticker',
    scoreTicker: 'INT 1 - 0 JUV',
    tonyBetOntario: '-140',
    betMgmOntario: '-165',
    edgeMarginPct: 4.5,
    aiActionDirective: '🔥 LIVE BUY',
    pickTeam: 'Inter Milan',
    periodOrClock: '2nd Half'
  },
  {
    id: 'game-live-8',
    sport: 'SOCCER',
    league: 'MLS',
    matchup: 'Inter Miami vs LA Galaxy',
    engineLayer: '🔴 LAYER 2: LIVE',
    timeMetric: '61:40 Live Ticker',
    scoreTicker: 'MIA 3 - 1 LAG',
    tonyBetOntario: '-180',
    betMgmOntario: '-215',
    edgeMarginPct: 5.2,
    aiActionDirective: '🔥 LIVE BUY',
    pickTeam: 'Inter Miami',
    periodOrClock: '2nd Half'
  },
  {
    id: 'game-live-9',
    sport: 'NHL',
    league: 'NHL',
    matchup: 'Edmonton Oilers @ Vancouver Canucks',
    engineLayer: '🔴 LAYER 2: LIVE',
    timeMetric: 'P2 11:20',
    scoreTicker: 'EDM 3 - 2 VAN',
    tonyBetOntario: '+120',
    betMgmOntario: '-105',
    edgeMarginPct: 5.5,
    aiActionDirective: '🔥 LIVE BUY',
    pickTeam: 'Edmonton Oilers',
    periodOrClock: '2nd Period'
  },
  {
    id: 'game-live-10',
    sport: 'NHL',
    league: 'NHL',
    matchup: 'Vegas Golden Knights @ Colorado Avalanche',
    engineLayer: '🔴 LAYER 2: LIVE',
    timeMetric: 'P3 06:14',
    scoreTicker: 'VGK 2 - 3 COL',
    tonyBetOntario: '-130',
    betMgmOntario: '-150',
    edgeMarginPct: 4.0,
    aiActionDirective: '🔥 LIVE BUY',
    pickTeam: 'Colorado Avalanche',
    periodOrClock: '3rd Period'
  },
  {
    id: 'game-live-11',
    sport: 'TENNIS',
    league: 'ATP Tour',
    matchup: 'Carlos Alcaraz vs Jannik Sinner',
    engineLayer: '🔴 LAYER 2: LIVE',
    timeMetric: 'Set 3 (4-3)',
    scoreTicker: 'ALC 6-4, 4-6, 4-3',
    tonyBetOntario: '+135',
    betMgmOntario: '+110',
    edgeMarginPct: 5.9,
    aiActionDirective: '🔥 LIVE BUY',
    pickTeam: 'Carlos Alcaraz',
    periodOrClock: 'Final Set'
  },

  // --- LAYER 1: UPCOMING SCHEDULED MATRICES ---
  {
    id: 'game-2',
    sport: 'NFL',
    league: 'NFL',
    matchup: 'Kansas City Chiefs @ Buffalo Bills',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    timeMetric: 'Today 16:25 EST',
    scoreTicker: 'Scheduled',
    tonyBetOntario: '-120',
    betMgmOntario: '+110',
    edgeMarginPct: 6.8,
    aiActionDirective: '🔥 FULL BUY',
    pickTeam: 'Kansas City Chiefs'
  },
  {
    id: 'game-up-1',
    sport: 'NFL',
    league: 'NFL',
    matchup: 'San Francisco 49ers @ Philadelphia Eagles',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    timeMetric: 'Tonight 20:20 EST',
    scoreTicker: 'Scheduled',
    tonyBetOntario: '+115',
    betMgmOntario: '-105',
    edgeMarginPct: 5.4,
    aiActionDirective: '🔥 FULL BUY',
    pickTeam: 'San Francisco 49ers'
  },
  {
    id: 'game-up-2',
    sport: 'NFL',
    league: 'NFL',
    matchup: 'Baltimore Ravens @ Cincinnati Bengals',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    timeMetric: 'Tomorrow 13:00 EST',
    scoreTicker: 'Scheduled',
    tonyBetOntario: '-110',
    betMgmOntario: '+105',
    edgeMarginPct: 4.9,
    aiActionDirective: '🔥 FULL BUY',
    pickTeam: 'Baltimore Ravens'
  },
  {
    id: 'game-up-3',
    sport: 'NFL',
    league: 'NFL',
    matchup: 'Detroit Lions @ Green Bay Packers',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    timeMetric: 'Tomorrow 16:25 EST',
    scoreTicker: 'Scheduled',
    tonyBetOntario: '-105',
    betMgmOntario: '-110',
    edgeMarginPct: 0.8,
    aiActionDirective: '❌ NO VALUE',
    pickTeam: 'Pass'
  },
  {
    id: 'game-up-4',
    sport: 'NFL',
    league: 'NFL',
    matchup: 'Dallas Cowboys @ New York Giants',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    timeMetric: 'Tonight 20:15 EST',
    scoreTicker: 'Scheduled',
    tonyBetOntario: '-145',
    betMgmOntario: '-165',
    edgeMarginPct: 3.9,
    aiActionDirective: '🔥 FULL BUY',
    pickTeam: 'Dallas Cowboys'
  },
  {
    id: 'game-5',
    sport: 'NHL',
    league: 'NHL',
    matchup: 'Toronto Maple Leafs @ Montreal Canadiens',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    timeMetric: 'Tonight 19:00 EST',
    scoreTicker: 'Scheduled',
    tonyBetOntario: '-135',
    betMgmOntario: '-115',
    edgeMarginPct: 4.1,
    aiActionDirective: '🔥 FULL BUY',
    pickTeam: 'Toronto Maple Leafs'
  },
  {
    id: 'game-up-5',
    sport: 'NHL',
    league: 'NHL',
    matchup: 'New York Rangers @ Boston Bruins',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    timeMetric: 'Tomorrow 19:00 EST',
    scoreTicker: 'Scheduled',
    tonyBetOntario: '+125',
    betMgmOntario: '+105',
    edgeMarginPct: 3.7,
    aiActionDirective: '🔥 FULL BUY',
    pickTeam: 'New York Rangers'
  },
  {
    id: 'game-up-6',
    sport: 'NHL',
    league: 'NHL',
    matchup: 'Calgary Flames @ Winnipeg Jets',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    timeMetric: 'Tonight 20:00 EST',
    scoreTicker: 'Scheduled',
    tonyBetOntario: '-125',
    betMgmOntario: '-140',
    edgeMarginPct: 2.8,
    aiActionDirective: '🔥 VALUE BUY',
    pickTeam: 'Winnipeg Jets'
  },
  {
    id: 'game-6',
    sport: 'MLB',
    league: 'MLB',
    matchup: 'New York Yankees @ Boston Red Sox',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    timeMetric: 'Tomorrow 13:05 EST',
    scoreTicker: 'Scheduled',
    tonyBetOntario: '+105',
    betMgmOntario: '-110',
    edgeMarginPct: 3.6,
    aiActionDirective: '🔥 FULL BUY',
    pickTeam: 'New York Yankees'
  },
  {
    id: 'game-up-7',
    sport: 'MLB',
    league: 'MLB',
    matchup: 'Houston Astros @ Seattle Mariners',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    timeMetric: 'Tonight 21:40 EST',
    scoreTicker: 'Scheduled',
    tonyBetOntario: '+135',
    betMgmOntario: '+110',
    edgeMarginPct: 5.1,
    aiActionDirective: '🔥 FULL BUY',
    pickTeam: 'Houston Astros'
  },
  {
    id: 'game-up-8',
    sport: 'MLB',
    league: 'MLB',
    matchup: 'Toronto Blue Jays @ Tampa Bay Rays',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    timeMetric: 'Tonight 19:07 EST',
    scoreTicker: 'Scheduled',
    tonyBetOntario: '-115',
    betMgmOntario: '+105',
    edgeMarginPct: 4.8,
    aiActionDirective: '🔥 FULL BUY',
    pickTeam: 'Toronto Blue Jays'
  },
  {
    id: 'game-7',
    sport: 'NBA',
    league: 'NBA',
    matchup: 'Los Angeles Lakers @ Golden State Warriors',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    timeMetric: 'Tomorrow 22:00 EST',
    scoreTicker: 'Scheduled',
    tonyBetOntario: '+130',
    betMgmOntario: '+125',
    edgeMarginPct: 0.9,
    aiActionDirective: '❌ NO VALUE',
    pickTeam: 'Pass'
  },
  {
    id: 'game-up-9',
    sport: 'NBA',
    league: 'NBA',
    matchup: 'Denver Nuggets @ Dallas Mavericks',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    timeMetric: 'Tonight 20:30 EST',
    scoreTicker: 'Scheduled',
    tonyBetOntario: '-110',
    betMgmOntario: '+110',
    edgeMarginPct: 5.7,
    aiActionDirective: '🔥 FULL BUY',
    pickTeam: 'Denver Nuggets'
  },
  {
    id: 'game-up-10',
    sport: 'NBA',
    league: 'NBA',
    matchup: 'Phoenix Suns @ Minnesota Timberwolves',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    timeMetric: 'Tomorrow 20:00 EST',
    scoreTicker: 'Scheduled',
    tonyBetOntario: '-135',
    betMgmOntario: '-155',
    edgeMarginPct: 4.3,
    aiActionDirective: '🔥 FULL BUY',
    pickTeam: 'Minnesota Timberwolves'
  },
  {
    id: 'game-up-11',
    sport: 'SOCCER',
    league: 'UEFA Champions League',
    matchup: 'Manchester City vs Real Madrid',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    timeMetric: 'Tomorrow 15:00 EST',
    scoreTicker: 'Scheduled',
    tonyBetOntario: '+115',
    betMgmOntario: '-110',
    edgeMarginPct: 7.1,
    aiActionDirective: '🔥 FULL BUY',
    pickTeam: 'Manchester City'
  },
  {
    id: 'game-up-12',
    sport: 'SOCCER',
    league: 'Premier League',
    matchup: 'Liverpool vs Manchester United',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    timeMetric: 'Sunday 11:30 EST',
    scoreTicker: 'Scheduled',
    tonyBetOntario: '-165',
    betMgmOntario: '-195',
    edgeMarginPct: 5.8,
    aiActionDirective: '🔥 FULL BUY',
    pickTeam: 'Liverpool'
  },
  {
    id: 'game-up-13',
    sport: 'SOCCER',
    league: 'Bundesliga',
    matchup: 'Bayern Munich vs Borussia Dortmund',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    timeMetric: 'Tomorrow 12:30 EST',
    scoreTicker: 'Scheduled',
    tonyBetOntario: '-170',
    betMgmOntario: '-200',
    edgeMarginPct: 4.6,
    aiActionDirective: '🔥 FULL BUY',
    pickTeam: 'Bayern Munich'
  },
  {
    id: 'game-up-14',
    sport: 'SOCCER',
    league: 'MLS',
    matchup: 'Toronto FC vs CF Montreal',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    timeMetric: 'Tomorrow 19:30 EST',
    scoreTicker: 'Scheduled',
    tonyBetOntario: '+120',
    betMgmOntario: '+105',
    edgeMarginPct: 3.4,
    aiActionDirective: '🔥 VALUE BUY',
    pickTeam: 'Toronto FC'
  },
  {
    id: 'game-up-15',
    sport: 'UFC',
    league: 'UFC 310',
    matchup: 'Jon Jones vs Stipe Miocic',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    timeMetric: 'Saturday 22:00 EST',
    scoreTicker: 'Scheduled',
    tonyBetOntario: '-450',
    betMgmOntario: '-550',
    edgeMarginPct: 8.2,
    aiActionDirective: '🔥 FULL BUY',
    pickTeam: 'Jon Jones'
  },
  {
    id: 'game-up-16',
    sport: 'UFC',
    league: 'UFC 310',
    matchup: 'Sean O\'Malley vs Merab Dvalishvili',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    timeMetric: 'Saturday 23:30 EST',
    scoreTicker: 'Scheduled',
    tonyBetOntario: '+135',
    betMgmOntario: '+110',
    edgeMarginPct: 4.5,
    aiActionDirective: '🔥 FULL BUY',
    pickTeam: 'Merab Dvalishvili'
  },
  {
    id: 'game-up-17',
    sport: 'TENNIS',
    league: 'ATP Tour',
    matchup: 'Novak Djokovic vs Daniil Medvedev',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    timeMetric: 'Tomorrow 14:00 EST',
    scoreTicker: 'Scheduled',
    tonyBetOntario: '-125',
    betMgmOntario: '-145',
    edgeMarginPct: 4.2,
    aiActionDirective: '🔥 FULL BUY',
    pickTeam: 'Novak Djokovic'
  }
];

export const INITIAL_LEDGER: SettledBet[] = [
  {
    timestamp: '2026-09-19 14:10:22',
    matchup: 'Houston Astros @ Texas Rangers',
    sport: 'MLB',
    aiPickSelection: 'Houston Astros',
    finalScoreLine: 'HOU 6 - 3 TEX',
    outcomeLabel: 'WIN (COVERED)',
    profitOrLoss: 85.00,
    runningBankroll: 1085.00
  },
  {
    timestamp: '2026-09-19 16:45:00',
    matchup: 'Baltimore Ravens @ Pittsburgh Steelers',
    sport: 'NFL',
    aiPickSelection: 'Baltimore Ravens',
    finalScoreLine: 'BAL 24 - 20 PIT',
    outcomeLabel: 'WIN (COVERED)',
    profitOrLoss: 95.50,
    runningBankroll: 1180.50
  },
  {
    timestamp: '2026-09-19 19:20:15',
    matchup: 'Denver Nuggets @ Dallas Mavericks',
    sport: 'NBA',
    aiPickSelection: 'Dallas Mavericks',
    finalScoreLine: 'DEN 112 - 108 DAL',
    outcomeLabel: 'LOSS (MISSED)',
    profitOrLoss: -60.00,
    runningBankroll: 1120.50
  },
  {
    timestamp: '2026-09-19 21:05:40',
    matchup: 'Liverpool vs Manchester City',
    sport: 'SOCCER',
    aiPickSelection: 'Liverpool',
    finalScoreLine: 'LIV 2 - 1 MCI',
    outcomeLabel: 'WIN (COVERED)',
    profitOrLoss: 120.00,
    runningBankroll: 1240.50
  }
];
