import { GameCard, SettledBet } from './types';

export const INITIAL_GAMES: GameCard[] = [
  {
    id: 'game-1',
    engineLayer: '🔴 LAYER 2: IN-PLAY LIVE',
    sport: 'BASEBALL',
    matchup: 'SF Giants @ LA Dodgers',
    timeMetric: 'Inning 3 - Active',
    scoreTicker: 'SF Giants 3 - 2 LA Dodgers',
    tonyBet: 'TonyBet (1.74)',
    tonyBetRaw: 1.74,
    betMgm: 'BetMGM (1.72)',
    betMgmRaw: 1.74,
    edgeMarginPct: 1.7,
    aiActionDirective: '🔥 LIVE BUY',
    pickTeam: 'SF Giants',
    homeTeam: 'LA Dodgers',
    awayTeam: 'SF Giants',
    homeScore: 2,
    awayScore: 3,
    elapsedSec: 180,
    durationSec: 540,
  },
  {
    id: 'game-2',
    engineLayer: '🔴 LAYER 2: IN-PLAY LIVE',
    sport: 'BASEBALL',
    matchup: 'St. Louis Cardinals @ Washington Nationals',
    timeMetric: 'Extra Inning Bottom',
    scoreTicker: 'Cardinals 5 - 8 Nationals',
    tonyBet: 'TonyBet (3.09)',
    tonyBetRaw: 3.09,
    betMgm: 'BetMGM (3.05)',
    betMgmRaw: 3.05,
    edgeMarginPct: 8.0,
    aiActionDirective: '🔥 LIVE BUY',
    pickTeam: 'Washington Nationals',
    homeTeam: 'Washington Nationals',
    awayTeam: 'St. Louis Cardinals',
    homeScore: 8,
    awayScore: 5,
    elapsedSec: 420,
    durationSec: 540,
  },
  {
    id: 'game-3',
    engineLayer: '🔴 LAYER 2: IN-PLAY LIVE',
    sport: 'BASEBALL',
    matchup: 'Arizona Diamondbacks @ New York Yankees',
    timeMetric: 'Break top 9 bottom 8',
    scoreTicker: 'D-backs 3 - 3 Yankees',
    tonyBet: 'TonyBet (2.00)',
    tonyBetRaw: 2.00,
    betMgm: 'BetMGM (1.98)',
    betMgmRaw: 1.98,
    edgeMarginPct: 3.2,
    aiActionDirective: '🔥 LIVE BUY',
    pickTeam: 'Arizona Diamondbacks',
    homeTeam: 'New York Yankees',
    awayTeam: 'Arizona Diamondbacks',
    homeScore: 3,
    awayScore: 3,
    elapsedSec: 300,
    durationSec: 540,
  },
  {
    id: 'game-4',
    engineLayer: '🔴 LAYER 2: IN-PLAY LIVE',
    sport: 'SOCCER',
    matchup: 'Orlando City SC @ Inter Miami CF',
    timeMetric: '68:51 Live Ticker',
    scoreTicker: 'Orlando City SC 1 - 4 Inter Miami CF',
    tonyBet: 'TonyBet (2.15)',
    tonyBetRaw: 2.15,
    betMgm: 'BetMGM (2.15)',
    betMgmRaw: 2.15,
    edgeMarginPct: 5.2,
    aiActionDirective: '🔥 LIVE BUY',
    pickTeam: 'Inter Miami CF',
    homeTeam: 'Inter Miami CF',
    awayTeam: 'Orlando City SC',
    homeScore: 4,
    awayScore: 1,
    elapsedSec: 4131,
    durationSec: 5400,
  },
  {
    id: 'game-5',
    engineLayer: '🔴 LAYER 2: IN-PLAY LIVE',
    sport: 'BASEBALL',
    matchup: 'Miami Marlins @ San Diego Padres',
    timeMetric: '7th inning top',
    scoreTicker: 'Marlins 5 - 6 Padres',
    tonyBet: 'TonyBet (1.14)',
    tonyBetRaw: 1.14,
    betMgm: 'BetMGM (1.15)',
    betMgmRaw: 1.15,
    edgeMarginPct: 2.1,
    aiActionDirective: '🔥 LIVE BUY',
    pickTeam: 'San Diego Padres',
    homeTeam: 'San Diego Padres',
    awayTeam: 'Miami Marlins',
    homeScore: 6,
    awayScore: 5,
    elapsedSec: 380,
    durationSec: 540,
  },
  {
    id: 'game-6',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    sport: 'FOOTBALL',
    matchup: 'Miami Dolphins @ San Francisco 49ers',
    timeMetric: 'SUN 04:25 p.m.',
    scoreTicker: 'PRE-MATCH SCHEDULE',
    tonyBet: 'TonyBet (7.25)',
    tonyBetRaw: 7.25,
    betMgm: 'BetMGM (7.25)',
    betMgmRaw: 7.25,
    edgeMarginPct: 4.6,
    aiActionDirective: '🔥 FULL BUY',
    pickTeam: 'San Francisco 49ers',
    homeTeam: 'San Francisco 49ers',
    awayTeam: 'Miami Dolphins',
  },
  {
    id: 'game-7',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    sport: 'FOOTBALL',
    matchup: 'New York Giants @ Los Angeles Rams',
    timeMetric: 'MON 08:15 p.m.',
    scoreTicker: 'PRE-MATCH SCHEDULE',
    tonyBet: 'TonyBet (2.88)',
    tonyBetRaw: 2.88,
    betMgm: 'BetMGM (2.82)',
    betMgmRaw: 2.82,
    edgeMarginPct: 7.1,
    aiActionDirective: '🔥 FULL BUY',
    pickTeam: 'Los Angeles Rams',
    homeTeam: 'Los Angeles Rams',
    awayTeam: 'New York Giants',
  },
  {
    id: 'game-8',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    sport: 'FOOTBALL',
    matchup: 'Jacksonville Jaguars @ Denver Broncos',
    timeMetric: 'SUN 04:05 p.m.',
    scoreTicker: 'PRE-MATCH SCHEDULE',
    tonyBet: 'TonyBet (2.37)',
    tonyBetRaw: 2.37,
    betMgm: 'BetMGM (2.35)',
    betMgmRaw: 2.37,
    edgeMarginPct: 7.2,
    aiActionDirective: '🔥 FULL BUY',
    pickTeam: 'Denver Broncos',
    homeTeam: 'Denver Broncos',
    awayTeam: 'Jacksonville Jaguars',
  },
  {
    id: 'game-9',
    engineLayer: '⏳ LAYER 1: UPCOMING',
    sport: 'BASKETBALL',
    matchup: 'Miami Heat @ Boston Celtics',
    timeMetric: 'TUE 07:30 p.m.',
    scoreTicker: 'PRE-MATCH SCHEDULE',
    tonyBet: 'TonyBet (1.55)',
    tonyBetRaw: 1.55,
    betMgm: 'BetMGM (1.52)',
    betMgmRaw: 1.52,
    edgeMarginPct: 5.8,
    aiActionDirective: '🔥 FULL BUY',
    pickTeam: 'Boston Celtics',
    homeTeam: 'Boston Celtics',
    awayTeam: 'Miami Heat',
  }
];

export const INITIAL_LEDGER: SettledBet[] = [
  {
    id: 'bet-1',
    timestamp: '2026-09-18 20:47',
    matchup: 'SF Giants @ LA Dodgers',
    sport: 'MLB',
    aiPickSelection: 'Target: LA Dodgers',
    finalScoreLine: 'SF Giants 2 - 6 LA Dodgers',
    outcomeLabel: '❌ LOSS MARKET EDGE',
    tradeOutcomeProfitLoss: -35.0,
    runningBankroll: 965.0,
  },
  {
    id: 'bet-2',
    timestamp: '2026-09-18 20:48',
    matchup: 'GS Warriors @ LA Lakers',
    sport: 'NBA',
    aiPickSelection: 'Target: LA Lakers',
    finalScoreLine: 'GS Warriors 96 - 104 LA Lakers',
    outcomeLabel: '🏆 WIN SYSTEM ORDER',
    tradeOutcomeProfitLoss: 75.0,
    runningBankroll: 1040.0,
  },
  {
    id: 'bet-3',
    timestamp: '2026-09-18 20:48',
    matchup: 'BUF Bills @ KC Chiefs',
    sport: 'NFL',
    aiPickSelection: 'Target: KC Chiefs',
    finalScoreLine: 'BUF Bills 21 - 33 KC Chiefs',
    outcomeLabel: '🏆 WIN SYSTEM ORDER',
    tradeOutcomeProfitLoss: 110.0,
    runningBankroll: 1150.0,
  },
  {
    id: 'bet-4',
    timestamp: '2026-09-18 20:49',
    matchup: 'TOR Maple Leafs @ EDM Oilers',
    sport: 'NHL',
    aiPickSelection: 'Target: EDM Oilers',
    finalScoreLine: 'TOR Maple Leafs 2 - 6 EDM Oilers',
    outcomeLabel: '🏆 WIN SYSTEM ORDER',
    tradeOutcomeProfitLoss: 45.0,
    runningBankroll: 1195.0,
  },
  {
    id: 'bet-5',
    timestamp: '2026-09-19 16:56',
    matchup: 'LSU @ Alabama',
    sport: 'FOOTBALL',
    aiPickSelection: 'Target: Alabama',
    finalScoreLine: 'LSU 20 - 31 Alabama',
    outcomeLabel: '🏆 WIN SYSTEM ORDER',
    tradeOutcomeProfitLoss: 75.0,
    runningBankroll: 1110.0,
  },
  {
    id: 'bet-6',
    timestamp: '2026-09-19 16:57',
    matchup: 'BOS Red Sox @ NY Yankees',
    sport: 'MLB',
    aiPickSelection: 'Target: NY Yankees',
    finalScoreLine: 'BOS Red Sox 7 - 2 NY Yankees',
    outcomeLabel: '❌ LOSS MARKET EDGE',
    tradeOutcomeProfitLoss: -80.0,
    runningBankroll: 1030.0,
  },
  {
    id: 'bet-7',
    timestamp: '2026-09-19 16:57',
    matchup: 'Jannik Sinner @ Carlos Alcaraz',
    sport: 'TENNIS',
    aiPickSelection: 'Target: Jannik Sinner',
    finalScoreLine: 'Jannik Sinner 5 - 4 Carlos Alcaraz',
    outcomeLabel: '❌ LOSS MARKET EDGE',
    tradeOutcomeProfitLoss: -35.0,
    runningBankroll: 995.0,
  },
  {
    id: 'bet-8',
    timestamp: '2026-09-19 16:57',
    matchup: 'Detroit Tigers @ Chicago White Sox',
    sport: 'MLB',
    aiPickSelection: 'Target: Detroit Tigers',
    finalScoreLine: 'Detroit Tigers 1 - 1 Chicago White Sox',
    outcomeLabel: '❌ LOSS MARKET EDGE',
    tradeOutcomeProfitLoss: -35.0,
    runningBankroll: 960.0,
  },
  {
    id: 'bet-9',
    timestamp: '2026-09-19 16:58',
    matchup: 'Nick Kyrgios @ Novak Djokovic',
    sport: 'TENNIS',
    aiPickSelection: 'Target: Novak Djokovic',
    finalScoreLine: 'Nick Kyrgios 1 - 2 Novak Djokovic',
    outcomeLabel: '❌ LOSS MARKET EDGE',
    tradeOutcomeProfitLoss: -60.0,
    runningBankroll: 900.0,
  },
  {
    id: 'bet-10',
    timestamp: '2026-09-19 16:58',
    matchup: 'Michigan @ Ohio State',
    sport: 'FOOTBALL',
    aiPickSelection: 'Target: Ohio State',
    finalScoreLine: 'Michigan 14 - 31 Ohio State',
    outcomeLabel: '❌ LOSS MARKET EDGE',
    tradeOutcomeProfitLoss: -35.0,
    runningBankroll: 865.0,
  },
  {
    id: 'bet-11',
    timestamp: '2026-09-19 16:59',
    matchup: 'Alexander Zverev @ Daniil Medvedev',
    sport: 'TENNIS',
    aiPickSelection: 'Target: Daniil Medvedev',
    finalScoreLine: 'Alexander Zverev 3 - 6 Daniil Medvedev',
    outcomeLabel: '🏆 WIN SYSTEM ORDER',
    tradeOutcomeProfitLoss: 110.0,
    runningBankroll: 975.0,
  },
  {
    id: 'bet-12',
    timestamp: '2026-09-19 16:59',
    matchup: 'TEX Rangers @ HOU Astros',
    sport: 'MLB',
    aiPickSelection: 'Target: TEX Rangers',
    finalScoreLine: 'TEX Rangers 1 - 1 HOU Astros',
    outcomeLabel: '❌ LOSS MARKET EDGE',
    tradeOutcomeProfitLoss: -35.0,
    runningBankroll: 940.0,
  },
  {
    id: 'bet-13',
    timestamp: '2026-09-19 16:59',
    matchup: 'STL Cardinals @ CHI Cubs',
    sport: 'MLB',
    aiPickSelection: 'Target: CHI Cubs',
    finalScoreLine: 'STL Cardinals 4 - 2 CHI Cubs',
    outcomeLabel: '❌ LOSS MARKET EDGE',
    tradeOutcomeProfitLoss: -80.0,
    runningBankroll: 860.0,
  },
  {
    id: 'bet-14',
    timestamp: '2026-09-19 17:00',
    matchup: 'Auburn @ Georgia',
    sport: 'FOOTBALL',
    aiPickSelection: 'Target: Georgia',
    finalScoreLine: 'Auburn 3 - 38 Georgia',
    outcomeLabel: '🏆 WIN SYSTEM ORDER',
    tradeOutcomeProfitLoss: 110.0,
    runningBankroll: 970.0,
  },
  {
    id: 'bet-15',
    timestamp: '2026-09-19 17:02',
    matchup: 'Ben Shelton @ Taylor Fritz',
    sport: 'TENNIS',
    aiPickSelection: 'Target: Ben Shelton',
    finalScoreLine: 'Ben Shelton 1 - 2 Taylor Fritz',
    outcomeLabel: '🏆 WIN SYSTEM ORDER',
    tradeOutcomeProfitLoss: 45.0,
    runningBankroll: 1015.0,
  },
  {
    id: 'bet-16',
    timestamp: '2026-09-19 17:02',
    matchup: 'NE Patriots @ BUF Bills',
    sport: 'FOOTBALL',
    aiPickSelection: 'Target: BUF Bills',
    finalScoreLine: 'NE Patriots 0 - 28 BUF Bills',
    outcomeLabel: '🏆 WIN SYSTEM ORDER',
    tradeOutcomeProfitLoss: 75.0,
    runningBankroll: 1090.0,
  },
  {
    id: 'bet-17',
    timestamp: '2026-09-19 23:16',
    matchup: 'Washington Nationals @ St. Louis Cardinals',
    sport: 'BASEBALL',
    aiPickSelection: 'Target: Washington Nationals',
    finalScoreLine: 'Washington Nationals 8 - 5 St. Louis Cardinals',
    outcomeLabel: '❌ LOSS MARKET EDGE',
    tradeOutcomeProfitLoss: -80.0,
    runningBankroll: 1010.0,
  },
  {
    id: 'bet-18',
    timestamp: '2026-09-19 23:16',
    matchup: 'New York Yankees @ Arizona Diamondbacks',
    sport: 'BASEBALL',
    aiPickSelection: 'Target: Arizona Diamondbacks',
    finalScoreLine: 'New York Yankees 3 - 3 Arizona Diamondbacks',
    outcomeLabel: '❌ LOSS MARKET EDGE',
    tradeOutcomeProfitLoss: -35.0,
    runningBankroll: 975.0,
  },
  {
    id: 'bet-19',
    timestamp: '2026-09-19 23:18',
    matchup: 'Miami Marlins @ San Diego Padres',
    sport: 'BASEBALL',
    aiPickSelection: 'Target: San Diego Padres',
    finalScoreLine: 'Miami Marlins 5 - 7 San Diego Padres',
    outcomeLabel: '🏆 WIN SYSTEM ORDER',
    tradeOutcomeProfitLoss: 110.0,
    runningBankroll: 1085.0,
  },
];
